Dodati signali i slotovi, ubaceni dugmici za prethodno i sljedece pitanje
sMirkovicc/qt_kviz pull request #1
Opened 2024-07-15 09:31 UTC by sMirkovicc

Takodje napravljeni i slotovi i signali za ucitavanje baze i kviza; i dugme zavrsi kviz

2024-07-15 11:03 UTC, RadeKornjaca requested changes
Dodatno, prepravi nazive promenljivih da budu isključivo na engleskom.

2024-07-15 11:03 UTC, RadeKornjaca commented on igra.cpp
> +    m_db.setDatabaseName("/home/Sara/saraqt/qt_kviz/database/kviz.db");
Znam da smo pokušavali, ali sad je vreme da se potraži da ovo bude ili relativno u odnosu na executable ili konfigurabilno (neki properties fajl ili šta već Qt može da ponudi na tu temu). Mislim konkretno na string putanje do fajla.

2024-07-15 11:03 UTC, RadeKornjaca commented on igra.cpp
> +    query1.prepare("SELECT IDKviza FROM kviz WHERE Naziv = '" + imeKviza + "'");
Možda ne bi bilo loše da istražiš da li ovaj string može da se zada na drugačiji način, pogotovo zato što je prepared statement u pitanju. Ovako napisan, deluje mi da je podložan SQL Injection tipu napada.

2024-07-15 11:03 UTC, RadeKornjaca commented on izbor.cpp
> +    if(i == 6)
Kviz može imati proizvoljan broj pitanja. Generalno, treba izbegavati tzv. magične brojeve. Odnosno, sve i da smo se dogovorili da kviz može imati fiksni broj pitanja, trebalo je onda napraviti konstantu u programu i dati joj smisleno ime.

2024-07-15 11:03 UTC, RadeKornjaca commented on izbor.cpp
> +    for(int k = 0; k < 7; k++)
Slična primedba ko i iznad, probaj bez magičnih brojeva.

2024-07-15 11:03 UTC, RadeKornjaca commented on izbor.h
> +    int odg[7];
Slična primedba, treba makar izdvojiti kao konstantu, ali bilo bi super da podržavaš i kvizove sa različitim brojem pitanja.

2024-07-15 11:03 UTC, RadeKornjaca commented on izbor.cpp
> +    }
Ovo bi mogla da bude posebna metoda.

2024-07-15 11:03 UTC, RadeKornjaca commented on izbor.cpp
> +    ui->comboBox_odgovori->setCurrentIndex(-1);
E, sad, pitanje je kako Qt funkcioniše i ti primeri koje si gledala. Neki stil koji sam usvojio je da u konstruktoru uglavnom bude minimalno stvari koje je potrebno inicijalizovati, pritom mislim na objekte.
Sve ove dodatne metode povezivanja signala i slotova, kao i setovanje slike i plejsholdera bi išli u neku posebnu metodu koja bi se pozvala nakon konstruktora.

Možeš ovde pročitati izabrani odgovor (za sad tebi Builder pattern ne treba), ali to je otprilike ideja koja je i meni poznata: https://stackoverflow.com/questions/3905784/what-not-to-do-in-a-constructor

2024-07-15 11:03 UTC, RadeKornjaca commented on izbor.cpp
> +    i++;
Možda bi ovo ``i`` moglo da bude malo deskriptivnije nazvano (indeks trenutnog pitanja ili nešto slično).

2024-07-18 12:01 UTC, RadeKornjaca requested changes
Najveći problem: konektovati se samo jednom na bazu i koristiti jednu konekciju u programu.

2024-07-18 12:01 UTC, RadeKornjaca commented on game.cpp
> +void Game::Init()
Nitpick: Ime metode treba da počne malim slovom.

2024-07-18 12:01 UTC, RadeKornjaca commented on game.cpp
> +void Game::quizIDLoading()
Isto tako, ako postoji neka skraćenica, poput ID, u camelCase-u će se pisati samo prvo slovo veliko: quizIdLoading.

2024-07-18 12:01 UTC, RadeKornjaca commented on highscore.cpp
> +void Highscore::Init()
Isto malim slovom.

2024-07-18 12:01 UTC, RadeKornjaca commented on highscore.cpp
> +        QSqlQuery query5("SELECT * FROM kviz");
Možda bi bilo neko deskriptivnije ime bolje, poput selectAllQuizesQuery.

2024-07-18 12:01 UTC, RadeKornjaca commented on highscore.cpp
> +        QSqlDatabase m_db = QSqlDatabase::addDatabase("QSQLITE");
Možemo li ovu bazu jednom da otvorimo, na jednom mestu, a da ostale klase koriste samo već otvorenu konekciju? Stalno konektovanje na bazu košta!

2024-07-18 12:01 UTC, RadeKornjaca commented on highscore.cpp
> +        QSqlQuery query6;
Isto deskriptivno ime.

2024-07-18 12:01 UTC, RadeKornjaca commented on highscore.cpp
> +        QSqlQuery query7;
Deskriptivno ime.

2024-07-18 12:01 UTC, RadeKornjaca commented on question.cpp
> +    for(int i = 0; i < 4; i++)
I dalje magični broj, zamisli da ti zatražim da promeniš broj pitanja? Morala bi po kodu da tražiš svuda gde si koristila i garant bi negde zaboravila da promeniš, pa bi imala bag. Uvesti konstantu.

2024-07-18 12:01 UTC, RadeKornjaca commented on question.cpp
> +    if(CorrectAnswer > 0 && CorrectAnswer < 5)
Iskoristiti novu konstantu od iznad.

2024-07-18 12:01 UTC, RadeKornjaca commented on question.cpp
> +        return 1;
Pošto je povratni tip ``bool``, staviti da su povratne vrednosti ``true`` i ``false``.

2024-07-18 12:01 UTC, RadeKornjaca commented on question.h
> +    QString m_ArrayOfAnswers[4];
Opet magični broj, možda ne bi bilo loše da veličina bude uvedena kao #define direktiva.

2024-07-18 12:01 UTC, RadeKornjaca commented on selection.cpp
> +void Selection::Init()
Malim slovom.

2024-07-18 12:01 UTC, RadeKornjaca commented on selection.cpp
> +void Selection::LoadQuizNameAndID(QString quizName, int ID)
Malim slovom ime metoda, treba biti konzistentan sa stilom.

2024-07-18 12:01 UTC, RadeKornjaca commented on selection.cpp
> +void Selection::LoadName(QString name)
Ovo je setter metoda, čini mi se da bi bolje ime bilo ``setName``.

2024-07-18 12:01 UTC, RadeKornjaca commented on selection.cpp
> +    }
Postoji li neki razlog zašto je ovo poseban programski blok?

2024-07-18 12:01 UTC, RadeKornjaca commented on selection.cpp
> +}
Pošto je kod jako sličan u sve tri metode, istražiti da li je moguće uz pomoć nekog parametra objediniti ponašanje u jednu metodu.

2024-07-18 12:01 UTC, RadeKornjaca commented on selection.h
> +    QString m_DBanswers[4];
Koristiti #define direktivu koju sam gore spomenuo.

2024-07-18 12:57 UTC, sMirkovicc commented on selection.cpp
> +    }
https://doc.qt.io/qt-6/qsqldatabase.html#removeDatabase
ovdje sam to vidjela

2024-07-18 18:43 UTC, RadeKornjaca commented on selection.cpp
> +    }
Jasno, kako db i query objekti nisu validni nakon zatvaranja, stavljanjem u posebni blok njihov životni vek je smanjen na unutar tog programskog bloka.
Malo je reći da mi je ideja bljuc, ali razumem zašto. :D

2024-07-18 18:43 UTC, RadeKornjaca commented on highscore.cpp
> +        QSqlDatabase m_db = QSqlDatabase::addDatabase("QSQLITE");
https://katecpp.github.io/sqlite-with-qt/

Ovde imaš primer kako bi to moglo da se uradi (ima i link ka Github repozitorijumu na dnu članka).

2024-07-22 16:22 UTC, merged